version: '3.6'

services:
  akhq:
    image: tchiotludo/akhq
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "localhost:29093" # kafka broker address
              schema-registry:
                url: "http://localhost:8081"  #schema registry address
              connect:
                - name: "connect"
                  url: "http://localhost:8085"  #kafka connect address
